image:
  - Ubuntu1804
  - Ubuntu
  - Visual Studio 2019 Preview
  - Visual Studio 2017
clone_depth: 10
configuration: Release
platform: AnyCPU
for:
  - matrix:
      only:
        - image: Ubuntu
    environment:
      GCC_VERSION: 5
  - matrix:
      only:
        - image: Ubuntu1804
    environment:
      GCC_VERSION: 7
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
        VC_VERSION: 15.0
        VC_PRERELEASE_ARGS:
  - matrix:
      only:
        - image: Visual Studio 2019 Preview
    environment:
        VC_VERSION: 16
        VC_PRERELEASE_ARGS: "--VisualC.discoverprereleases"
install:
  - sh: sudo apt-get -q update
  - sh: sudo apt-get -q -y --no-install-recommends install g++ gcc-multilib g++-multilib python libx11-dev libx11-dev:i386 libgl1-mesa-dev
  - cmd: curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.68.0/windows/VulkanSDK-1.0.68.0-Installer.exe?Human=true
  - cmd: .\VulkanSDK.exe /S
  - sh: wget -O vulkansdk-linux-x86_64-1.0.68.0.run https://vulkan.lunarg.com/sdk/download/1.0.68.0/linux/vulkansdk-linux-x86_64-1.0.68.0.run?Human=true
  - sh: chmod ugo+x vulkansdk-linux-x86_64-1.0.68.0.run
  - sh: ./vulkansdk-linux-x86_64-1.0.68.0.run
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - cmd: 7z x bam.tar -oc:\BuildAMation
  - sh: mkdir ~/BuildAMation
  - sh: tar xf bam.tar -C ~/BuildAMation
build: off
#test_script:
#  - cmd: c:\BuildAMation\env.bat
#  - cmd: "SET PATH=C:\\Python27-x64;%PATH%"
#  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
#  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b VSSolution -c debug -c profile -j0 -d --nodefaultrepo -r .
#  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b MakeFile -c debug -c profile -j0 -d --MakeFile.format=NMAKE --nodefaultrepo -r .
#  - sh: source ~/BuildAMation/env.sh
#  - sh: python ~/BuildAMation/tests/runtests.py --Gcc.version=$GCC_VERSION -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
#  - sh: python ~/BuildAMation/tests/runtests.py --Gcc.version=$GCC_VERSION -b MakeFile -c debug -c profile -j0 -d --nodefaultrepo -r .
